---
- src: geerlingguy.apache
- src: geerlingguy.php-versions
- src: geerlingguy.php
- src: geerlingguy.apache-php-fpm
- src: geerlingguy.mysql
- src: geerlingguy.composer
- src: geerlingguy.php-redis
- src: geerlingguy.php-mysql
- src: geerlingguy.php-memcached
- src: geerlingguy.memcached
- src: geerlingguy.php-xdebug